const registrationOptions = {
    // The challenge is produced by the server; see the Security Considerations
    challenge: new Uint8Array([21, 31, 105 /* 29 more random bytes generated by the server */]),
    // Relying Party:
    rp: {
        id: "ribstgnew.icicibank.com",
        name: "ICICI Bank Limited"
    },
    // User:
    user: {
        id: Uint8Array.from(window.atob("MICICIBankDataAjJohnDoewggE4oAMCAQIwggGTMII="), c => c.charCodeAt(0)),
        name: "john_doe@icicibank.com",
        displayName: "John Doe",
    },
    // This Relying Party will accept either an ES256 or RS256 credential, but
    // prefers an ES256 credential.
    pubKeyCredParams: [
        {
            type: "public-key",
            alg: -7 // "ES256" as registered in the IANA COSE Algorithms registry
        },
        {
            type: "public-key",
            alg: -257 // Value registered by this specification for "RS256"
        }
    ],
    authenticatorSelection: {
        // only stick to device specific authentication like Windows Hello / TouchID / FingerPrint authentication
        authenticatorAttachment: 'platform', // Corrected property name
    },
    timeout: 360000,  // 6 minutes
};

const loginOptions = {
    challenge: new Uint8Array([21, 31, 105 /* 29 more random bytes generated by the server */]),
    timeout: 360000,  // 6 minutes
    rpId: "ribstgnew.icicibank.com",

    authenticatorSelection: {
        userVerification: "preferred"
    },
}

export { registrationOptions, loginOptions }